#!/bin/sh
set -e -u -x

echo "Creating Generate ClIENT ID SECRET Client..."
  uaac target ${UAA_ENDPOINT} --skip-ssl-validation
  uaac token client get admin -s ${UAA_ADMIN_SECRET}
  uaac client add ${CF_CLIENT_ID} \
        --secret ${CF_CLIENT_SECRET} \
        --authorized_grant_types client_credentials,refresh_token \
        --authorities cloud_controller.read || true

uaac token client get ${CF_CLIENT_ID} -s ${CF_CLIENT_SECRET}
