cf-api-w-scheme:
cf-api:
cf-client-id:
cf-client-secret:
cf-org:
cf-password:
cf-space-dev:
cf-username:
debug:
opsmanager-admin-password:
opsmanager-admin-user:
opsmanager-client-id:
opsmanager-client-secret:
opsmanager-endpoint:
pivnet-api-token:
private-key-github-concourse:
skip-ssl-validation:
uaa-admin-crend-secret:
uaa-endpoint:
